# Generated by Django 5.0.2 on 2024-03-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='type',
            field=models.CharField(default='Colour', max_length=255),
            preserve_default=False,
        ),
    ]
