# Generated by Django 5.0.2 on 2024-04-08 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_pounds',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_delta_pounds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(-999999.99), django.core.validators.MaxValueValidator(999999.99)]),
            preserve_default=False,
        ),
    ]
