# Generated by Django 5.0.2 on 2024-04-15 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_price_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, 'Placed'), (1, 'Paid'), (2, 'Out For Delivery'), (3, 'Delivered'), (4, 'Received')], default=0),
        ),
    ]
