# Generated by Django 5.0.2 on 2024-02-28 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food diaries',
            },
        ),
        migrations.CreateModel(
            name='FoodDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meal', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snacks')], default=4)),
                ('calories', models.IntegerField()),
                ('carbs_grams', models.IntegerField()),
                ('fat_grams', models.IntegerField()),
                ('protein_grams', models.IntegerField()),
                ('sodium_milligrams', models.IntegerField()),
                ('sugar_grams', models.IntegerField()),
                ('food_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_diary.fooddiary')),
            ],
            options={
                'verbose_name_plural': 'Food diary entries',
            },
        ),
    ]
