# Generated by Django 5.0.2 on 2024-02-27 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('carbs_grams', models.IntegerField()),
                ('fat_grams', models.IntegerField()),
                ('protein_grams', models.IntegerField()),
                ('sodium_milligrams', models.IntegerField()),
                ('sugar_grams', models.IntegerField()),
                ('food_diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.fooddiary')),
            ],
        ),
    ]
