# Generated by Django 5.0.2 on 2024-02-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddiaryentry',
            options={'verbose_name_plural': 'FoodDiaryEntries'},
        ),
        migrations.RenameField(
            model_name='fooddiaryentry',
            old_name='food_diary_id',
            new_name='food_diary',
        ),
    ]
