# Generated by Django 5.0.2 on 2024-02-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_alter_fooddiaryentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddiary',
            options={'verbose_name_plural': 'Food diaries'},
        ),
        migrations.AlterModelOptions(
            name='fooddiaryentry',
            options={'verbose_name_plural': 'Food diary entries'},
        ),
    ]
