# Generated by Django 5.0.2 on 2024-02-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_alter_fooddiary_options_alter_fooddiaryentry_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fooddiary',
            table='food_diary',
        ),
        migrations.AlterModelTable(
            name='fooddiaryentry',
            table='food_diary_entry',
        ),
    ]
