# Generated by Django 5.0.2 on 2024-02-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_alter_fooddiary_table_alter_fooddiaryentry_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fooddiary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fooddiaryentry',
            table=None,
        ),
    ]
