# Generated by Django 5.0.2 on 2024-02-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_alter_fooddiary_table_alter_fooddiaryentry_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddiaryentry',
            name='meal',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snacks')], default=4),
        ),
    ]
