# Generated by Django 5.0.2 on 2024-02-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0006_fooddiaryentry_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiaryentry',
            name='food_diary',
        ),
        migrations.DeleteModel(
            name='FoodDiary',
        ),
        migrations.DeleteModel(
            name='FoodDiaryEntry',
        ),
    ]
